# Generated by Django 3.2.23 on 2024-01-23 15:31

import cloudinary.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraft_type', models.CharField(max_length=100)),
                ('seats', models.CharField(choices=[('2', '2'), ('4', '4')], default='2', max_length=1)),
                ('engines', models.CharField(choices=[('1', '1'), ('2', '2')], default='1', max_length=1)),
            ],
            options={
                'ordering': ['aircraft_type'],
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('duration', models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(30)])),
                ('cost', models.PositiveIntegerField()),
                ('image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('aircraft_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.aircraft')),
            ],
            options={
                'ordering': ['cost'],
            },
        ),
    ]
