# Generated by Django 3.2.23 on 2024-02-05 19:36

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flights', '0003_alter_voucher_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('licence_type', models.CharField(max_length=100)),
                ('cost', models.PositiveIntegerField()),
                ('mode_of_training', models.CharField(max_length=40)),
                ('image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('aircraft_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.aircraft')),
            ],
            options={
                'ordering': ['cost'],
            },
        ),
    ]
