# Generated by Django 3.2.23 on 2024-02-05 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Licence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licence_type', models.CharField(max_length=100)),
                ('required_flight_time', models.PositiveIntegerField()),
                ('engines', models.CharField(choices=[('1', '1'), ('2', '2')], default='1', max_length=1)),
            ],
            options={
                'ordering': ['required_flight_time'],
            },
        ),
        migrations.AlterModelOptions(
            name='training',
            options={'ordering': ['cost'], 'verbose_name_plural': 'Training'},
        ),
        migrations.AlterField(
            model_name='training',
            name='licence_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.licence'),
        ),
    ]
