# Generated by Django 3.2.23 on 2024-02-07 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_alter_licence_required_flight_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='mode_of_training',
            field=models.CharField(choices=[('Modular', 'Integrated')], default='Modular', max_length=50),
        ),
    ]
