# Generated by Django 3.2.23 on 2024-02-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_alter_training_mode_of_training'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='mode_of_training',
            field=models.CharField(choices=[('Modular', 'Modular'), ('Integrated', 'Integrated')], default='Modular', max_length=50),
        ),
    ]
